_BASE_: "../oicr_WSR_18_DC5_1x.yaml"
WSL:
  REFINE_NUM: 4
  REFINE_REG: [True, True, True, True]
  RPN:
    WARMUP: False
    WARMUP_ITERS: 50000
MODEL:
  PROPOSAL_GENERATOR:
    NAME: "RPNWSL"
    MIN_SIZE: 20
  RPN:
    IN_FEATURES: ["res5"]
    PRE_NMS_TOPK_TRAIN: 40960
    PRE_NMS_TOPK_TEST: 40960
    POST_NMS_TOPK_TRAIN: 2048
    POST_NMS_TOPK_TEST: 2048
    NMS_THRESH: 0.8
  ROI_HEADS:
    NAME: "RPNOICRROIHeads"
